ptext = choose(
"AN APPLE A DAY KEEPS THE DOCTOR AWAY",
"HEY, WHERE YA GOIN?",
"REMEMBER TO PUT SEMICOLONS!",
"THESE JOKES ARE GIVING ME CANCER!",
"CONSTRUCTING ADDITIONAL PYLONS!",
"GOTTA TIGHTEN UP THE GRAPHICS ON LEVEL 3");
